CXX      := g++
CXXFLAGS := -std=c++17 -Wall -Wextra -I./include -I./include/raylib -I./include/webview
LDFLAGS  := -L./lib/win_x86_64 -lraylib -lopengl32 -lgdi32 -lwinmm -lws2_32 -lole32 -loleaut32 -ladvapi32 -lversion -luuid -lshlwapi -lwebview2loader -static-libgcc -static-libstdc++

TARGET   := chainlang.exe
SRCDIR   := src
OBJDIR   := obj

SRCS := $(wildcard $(SRCDIR)/*.cpp)
OBJS := $(patsubst $(SRCDIR)/%.cpp, $(OBJDIR)/%.o, $(SRCS))

.PHONY: all build clean release

all: build

build: $(TARGET)

$(TARGET): $(OBJS)
	@echo Linking $(TARGET)...
	@$(CXX) $(CXXFLAGS) $^ $(LDFLAGS) -o $@

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp | $(OBJDIR)
	@echo Compiling $<...
	@$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJDIR):
	@mkdir -p $(OBJDIR)

release: CXXFLAGS += -O2 -DNDEBUG
release: build

clean:
	@rm -rf $(OBJDIR) $(TARGET) error.txt
	@echo Cleaned.